# Generated by Django 5.2.6 on 2025-09-23 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authe", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="signup_model",
        ),
    ]
